<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <style>
        /*404页面访问不存在*/
        .err_bg{background: #f5f5f5;padding: 37px 0 79px;margin-bottom: -50px;font-family: "Microsoft YaHei", "微软雅黑"}
        .err_404{height: 560px;width: 100%;background: #fff;text-align: center;padding-top:195px; }
        .err_404 img{width: 520px;height: 200px;}
        .err_404 p{text-align: center;}
        .err_404 p.hint_txt{font-size: 16px;color: #666;padding: 60px 0 30px;}
        .err_404 p.btn_home a{display:inline-block;width: 111px;height: 32px;text-align: center;line-height: 32px;color: #f04042;font-size:14px;border: 1px solid #f04042; }
    </style>
</head>
<body>
<div class="err_bg">
    <div class="wrap">
        <div class="err_404">
            <img src="/res/Common/images/404.jpg" alt="">
            <p class="hint_txt">抱歉，您指定的页面暂时无法访问哦。</p>
            <p class="btn_home"><a href="/home/index/index">返回首页</a></p>
        </div>
    </div>
</div>
</body>
</html>