<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>身高管理-添加测量</title>
</head>
<body>
    <div>
        <p>姓名：
        </p>
        <p>最后一次测量身高：125cm</p>
        <p><a href="#">测量</a></p>
        <form action="">
        <table>
<!--            <tr>-->
<!--                <td>姓名</td>-->
<!--                <td>-->
<!--                    <select name="user" id="">-->
<!--                        <option value="1">黄紫淇</option>-->
<!--                        <option value="2">黄紫涵</option>-->
<!--                    </select>-->
<!--                </td>-->
<!--            </tr>-->
            <tr>
                <td>身高(cm)</td>
                <td><input type="text" ></td>
            </tr>
            <tr>
                <td><input type="submit"></td>
            </tr>
        </table>
        </form>
    </div>
</body>
</html>