TTTTTT!!!
<?php
echo $testA; die;
?>
<div id="searchFormA">
    <form id="searchForm_" action="#" method="get">
        姓名:<br>
        <input type="text" name="name" value="Mickey">
        <br>
        性别:<br>
        <input type="radio" name="sex" value="male">男,
        <input type="radio" name="sex" value="female">女
        <br>
        兴趣：<br>
        <input type="checkbox" name="run" >跑步
        <input type="checkbox" name="swim" >游泳
        <input type="checkbox" name="basketBall" >篮球
        <br>
        所属年级：<br>
        <select name="level">
            <option value="1">一年级</option>
            <option value="2">二年级</option>
            <option value="3">三年级</option>
            <option value="4">四年级</option>
            <option value="5">五年级</option>
            <option value="6">六年级</option>
        </select>
        <br><br>

        <input type="submit" value="提交(submit)">
    <!--    <button>提交2</button>-->
    </form>
</div>
<hr>